title: Mike Tsai
subtitle: Cheng-Yu (Mike) Tsai is a prospective PhD student in EE/CS, interested in computer architecture.
description: >- # this means to ignore newlines until "baseurl:"
  # devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "https://mike84265.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: About
      url: /
    - text: Research
      url: /research

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.jpg
author: Mike Tsai
author_bio: Cheng-Yu (Mike) Tsai is a prospective PhD student in EE/CS, interested in computer architecture.
author_email: "iijft1111@gmail.com"
author_location: Hsinchu, Taiwan
author_website_url: "https://mike84265.github.io"
typewrite-text: Cheng-Yu (Mike) Tsai is a prospective PhD student in EE/CS, interested in computer architecture.
hero_cover_img: pinglin.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Taiwan Semiconductor Manufacturing Company
              company_logo: TSMC-Logo.png
              company_url: https://tsmc.com/
              designation: Engineer
              description: Custom Design Flow Development Department, DTP, R&D
              period: "Jul '21 - present"
              visibility: true
            - company_name: National Taiwan University
              company_logo: NTU-Logo.png
              company_url: https://www.ntu.edu.tw
              designation: Part-time worker
              description: Division of Network Management, Computer Information & Network Center
              period: "Apr '18 - Jan '21"
              visibility: true

# Education
author_education_details:
              - college_name: National Taiwan University
                college_logo: NTU-Logo.png
                college_url: https://www.ntu.edu.tw
                college_degree: Computer Science and Information Engineering
                description: Master of Science
                period: "Jan '19 - Jun '21"
                visibility: true

              - college_name: National Taiwan University
                college_logo: NTU-Logo.png
                college_url: https://www.ntu.edu.tw
                college_degree: Electrical Engineering
                description: Bachelor of Science in Engineering
                period: "Sep '14 - Jan '19"
                visibility: true

              - college_name: National Taiwan University
                college_logo: NTU-Logo.png
                college_url: https://www.ntu.edu.tw
                college_degree: Computer Science and Information Engineering
                description: Bachelor of Science
                period: "Sep '14 - Jan '19"
                visibility: true

# Projects
author_project_details:
              - project_title: Delay Calculator
                project_description: A fast propagation delay estimator for standard cells
                project_url: /delay_calculator.html
                project_affiliation: "TSMC, Jun '22 - Jul '23"
                project_thumbnail: TSMC-Logo.png
                visibility: true

              - project_title: Performance Analytical Model 
                project_description: An analytical model for estimating tradeoffs between cache capacity and memory bandwidth
                project_url: /cache_model.html
                project_affiliation: "NTU CSIE, Jan '19 - Jun '21"
                project_thumbnail: NTU-Logo.png
                visibility: true

              - project_title: Campus-wide Wi-Fi Monitoring and Visualization Framework
                project_description: A framework for monitoring service quality of APs in the campus
                project_affiliation: "NTU Computer Information and Network Center, Apr '18 - Jan '21 "
                project_url: /ntu_ap_monitor.html
                project_thumbnail: NTU-Logo.png
                visibility: true


#               - project_thumbnail: gamershub.png
#                 project_title: Gamers Hub
#                 project_description: A Platform built for Gamers and Game Devs
#                 project_url: https://gamershub.in
#                 visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: MikeTsai986604
github_username:  mike84265
# facebook_username: johndoe
linkedin_username: "cheng-yu-tsai-b65194230"
# behance_username: johndoe
instagram_username: "c.y.tsai_1001"
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
flickr_username: "143304545@N08"

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
# formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
# olvy_organization: devlopr
# olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md
  - run.sh


destination: ./build
